version: '3'

services: 
    keycloak:
        image: quay.io/keycloak/keycloak:11.0.1
        environment: 
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
        ports: 
            - 8080:8080

    golang:
        build: .
        ports: 
            - 8081:8080